// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.36.1
// source: worker/v1/worker.proto

// Package worker.v1 is the wire surface of the SAFER worker service
// (cmd/worker).
//
// The worker is a stateless adapter around the existing SAFER client
// package (github.com/JamJamzzz/safer-distributed/client): every RPC opens
// or reuses this process's MongoDB and coordinator connections and calls
// straight into the same InitUser/StoreFile/AppendToFile/LoadFile logic
// SAFER-CC has always had. No new cryptography, storage, or locking
// semantics are introduced here.
//
// The surface is intentionally the minimum needed to drive a realistic
// deployment/load test, not a mechanical export of every SAFER method.
//
// Every RPC carries the caller's username and password: SAFER derives a
// user's keys from that pair on every call rather than keeping
// server-side session state (see client.GetUser), so the worker itself
// holds no per-user state between requests and any replica can serve any
// request.

package workerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SaferWorker_InitUser_FullMethodName     = "/worker.v1.SaferWorker/InitUser"
	SaferWorker_StoreFile_FullMethodName    = "/worker.v1.SaferWorker/StoreFile"
	SaferWorker_AppendToFile_FullMethodName = "/worker.v1.SaferWorker/AppendToFile"
	SaferWorker_LoadFile_FullMethodName     = "/worker.v1.SaferWorker/LoadFile"
)

// SaferWorkerClient is the client API for SaferWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SaferWorkerClient interface {
	InitUser(ctx context.Context, in *InitUserRequest, opts ...grpc.CallOption) (*InitUserResponse, error)
	StoreFile(ctx context.Context, in *StoreFileRequest, opts ...grpc.CallOption) (*StoreFileResponse, error)
	AppendToFile(ctx context.Context, in *AppendToFileRequest, opts ...grpc.CallOption) (*AppendToFileResponse, error)
	LoadFile(ctx context.Context, in *LoadFileRequest, opts ...grpc.CallOption) (*LoadFileResponse, error)
}

type saferWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewSaferWorkerClient(cc grpc.ClientConnInterface) SaferWorkerClient {
	return &saferWorkerClient{cc}
}

func (c *saferWorkerClient) InitUser(ctx context.Context, in *InitUserRequest, opts ...grpc.CallOption) (*InitUserResponse, error) {
	out := new(InitUserResponse)
	err := c.cc.Invoke(ctx, SaferWorker_InitUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saferWorkerClient) StoreFile(ctx context.Context, in *StoreFileRequest, opts ...grpc.CallOption) (*StoreFileResponse, error) {
	out := new(StoreFileResponse)
	err := c.cc.Invoke(ctx, SaferWorker_StoreFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saferWorkerClient) AppendToFile(ctx context.Context, in *AppendToFileRequest, opts ...grpc.CallOption) (*AppendToFileResponse, error) {
	out := new(AppendToFileResponse)
	err := c.cc.Invoke(ctx, SaferWorker_AppendToFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saferWorkerClient) LoadFile(ctx context.Context, in *LoadFileRequest, opts ...grpc.CallOption) (*LoadFileResponse, error) {
	out := new(LoadFileResponse)
	err := c.cc.Invoke(ctx, SaferWorker_LoadFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SaferWorkerServer is the server API for SaferWorker service.
// All implementations must embed UnimplementedSaferWorkerServer
// for forward compatibility
type SaferWorkerServer interface {
	InitUser(context.Context, *InitUserRequest) (*InitUserResponse, error)
	StoreFile(context.Context, *StoreFileRequest) (*StoreFileResponse, error)
	AppendToFile(context.Context, *AppendToFileRequest) (*AppendToFileResponse, error)
	LoadFile(context.Context, *LoadFileRequest) (*LoadFileResponse, error)
	mustEmbedUnimplementedSaferWorkerServer()
}

// UnimplementedSaferWorkerServer must be embedded to have forward compatible implementations.
type UnimplementedSaferWorkerServer struct {
}

func (UnimplementedSaferWorkerServer) InitUser(context.Context, *InitUserRequest) (*InitUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitUser not implemented")
}
func (UnimplementedSaferWorkerServer) StoreFile(context.Context, *StoreFileRequest) (*StoreFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreFile not implemented")
}
func (UnimplementedSaferWorkerServer) AppendToFile(context.Context, *AppendToFileRequest) (*AppendToFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendToFile not implemented")
}
func (UnimplementedSaferWorkerServer) LoadFile(context.Context, *LoadFileRequest) (*LoadFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadFile not implemented")
}
func (UnimplementedSaferWorkerServer) mustEmbedUnimplementedSaferWorkerServer() {}

// UnsafeSaferWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SaferWorkerServer will
// result in compilation errors.
type UnsafeSaferWorkerServer interface {
	mustEmbedUnimplementedSaferWorkerServer()
}

func RegisterSaferWorkerServer(s grpc.ServiceRegistrar, srv SaferWorkerServer) {
	s.RegisterService(&SaferWorker_ServiceDesc, srv)
}

func _SaferWorker_InitUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaferWorkerServer).InitUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SaferWorker_InitUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaferWorkerServer).InitUser(ctx, req.(*InitUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SaferWorker_StoreFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaferWorkerServer).StoreFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SaferWorker_StoreFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaferWorkerServer).StoreFile(ctx, req.(*StoreFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SaferWorker_AppendToFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendToFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaferWorkerServer).AppendToFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SaferWorker_AppendToFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaferWorkerServer).AppendToFile(ctx, req.(*AppendToFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SaferWorker_LoadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaferWorkerServer).LoadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SaferWorker_LoadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaferWorkerServer).LoadFile(ctx, req.(*LoadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SaferWorker_ServiceDesc is the grpc.ServiceDesc for SaferWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SaferWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "worker.v1.SaferWorker",
	HandlerType: (*SaferWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitUser",
			Handler:    _SaferWorker_InitUser_Handler,
		},
		{
			MethodName: "StoreFile",
			Handler:    _SaferWorker_StoreFile_Handler,
		},
		{
			MethodName: "AppendToFile",
			Handler:    _SaferWorker_AppendToFile_Handler,
		},
		{
			MethodName: "LoadFile",
			Handler:    _SaferWorker_LoadFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "worker/v1/worker.proto",
}
