// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: coordinator/v1/coordinator.proto

// Package coordinator.v1 is the wire surface of the SAFER lock
// coordinator.
//
// The surface is deliberately small and strict-2PL-shaped.
//
// There is no BeginTransaction RPC. A transaction's identity is a UUID the
// worker generates locally, which costs nothing and cannot collide across
// workers; the coordinator creates transaction state lazily on the first
// Acquire. A separate Begin would add a round trip and a second failure
// mode (a transaction that exists on the coordinator but whose creating
// worker never learned it) for no gain in this phase.
//
// There is no per-resource Release. Under strict two-phase locking a
// transaction holds every lock it takes until it ends, so the only way to
// release is EndTransaction, which releases all of them at once. Offering
// early release would hand callers a way to violate the protocol.
//
// There is no lease or fencing-token machinery yet. That is the next
// phase, and its absence is the reason a crashed worker can still leak
// locks here.

package coordinatorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LockMode mirrors lockmanager.LockMode. UNSPECIFIED exists so that a
// caller that forgets to set the field is rejected rather than silently
// treated as a shared request.
type LockMode int32

const (
	LockMode_LOCK_MODE_UNSPECIFIED LockMode = 0
	LockMode_LOCK_MODE_SHARED      LockMode = 1
	LockMode_LOCK_MODE_EXCLUSIVE   LockMode = 2
)

// Enum value maps for LockMode.
var (
	LockMode_name = map[int32]string{
		0: "LOCK_MODE_UNSPECIFIED",
		1: "LOCK_MODE_SHARED",
		2: "LOCK_MODE_EXCLUSIVE",
	}
	LockMode_value = map[string]int32{
		"LOCK_MODE_UNSPECIFIED": 0,
		"LOCK_MODE_SHARED":      1,
		"LOCK_MODE_EXCLUSIVE":   2,
	}
)

func (x LockMode) Enum() *LockMode {
	p := new(LockMode)
	*p = x
	return p
}

func (x LockMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LockMode) Descriptor() protoreflect.EnumDescriptor {
	return file_coordinator_v1_coordinator_proto_enumTypes[0].Descriptor()
}

func (LockMode) Type() protoreflect.EnumType {
	return &file_coordinator_v1_coordinator_proto_enumTypes[0]
}

func (x LockMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LockMode.Descriptor instead.
func (LockMode) EnumDescriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{0}
}

// ResourceType mirrors lockmanager.ResourceType. The coordinator never
// branches on it; it is part of the resource's identity.
type ResourceType int32

const (
	ResourceType_RESOURCE_TYPE_UNSPECIFIED ResourceType = 0
	ResourceType_RESOURCE_TYPE_NAMESPACE   ResourceType = 1
	ResourceType_RESOURCE_TYPE_FILE        ResourceType = 2
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0: "RESOURCE_TYPE_UNSPECIFIED",
		1: "RESOURCE_TYPE_NAMESPACE",
		2: "RESOURCE_TYPE_FILE",
	}
	ResourceType_value = map[string]int32{
		"RESOURCE_TYPE_UNSPECIFIED": 0,
		"RESOURCE_TYPE_NAMESPACE":   1,
		"RESOURCE_TYPE_FILE":        2,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_coordinator_v1_coordinator_proto_enumTypes[1].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_coordinator_v1_coordinator_proto_enumTypes[1]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{1}
}

// ResourceId identifies one logical lockable resource, exactly as
// lockmanager.ResourceID does. The key is derived by the worker from
// SAFER's own canonical encoding; the coordinator treats it as opaque.
type ResourceId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type ResourceType `protobuf:"varint,1,opt,name=type,proto3,enum=coordinator.v1.ResourceType" json:"type,omitempty"`
	Key  string       `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ResourceId) Reset() {
	*x = ResourceId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordinator_v1_coordinator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceId) ProtoMessage() {}

func (x *ResourceId) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceId.ProtoReflect.Descriptor instead.
func (*ResourceId) Descriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceId) GetType() ResourceType {
	if x != nil {
		return x.Type
	}
	return ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *ResourceId) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type AcquireRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// transaction_id is a UUID generated by the worker. The coordinator
	// creates transaction state on first use and maps it to an internal
	// lock-manager transaction id.
	TransactionId string      `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Resource      *ResourceId `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Mode          LockMode    `protobuf:"varint,3,opt,name=mode,proto3,enum=coordinator.v1.LockMode" json:"mode,omitempty"`
}

func (x *AcquireRequest) Reset() {
	*x = AcquireRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordinator_v1_coordinator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcquireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireRequest) ProtoMessage() {}

func (x *AcquireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireRequest.ProtoReflect.Descriptor instead.
func (*AcquireRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *AcquireRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *AcquireRequest) GetResource() *ResourceId {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *AcquireRequest) GetMode() LockMode {
	if x != nil {
		return x.Mode
	}
	return LockMode_LOCK_MODE_UNSPECIFIED
}

type AcquireResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AcquireResponse) Reset() {
	*x = AcquireResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordinator_v1_coordinator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcquireResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireResponse) ProtoMessage() {}

func (x *AcquireResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireResponse.ProtoReflect.Descriptor instead.
func (*AcquireResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{2}
}

type EndTransactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionId string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
}

func (x *EndTransactionRequest) Reset() {
	*x = EndTransactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordinator_v1_coordinator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndTransactionRequest) ProtoMessage() {}

func (x *EndTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndTransactionRequest.ProtoReflect.Descriptor instead.
func (*EndTransactionRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *EndTransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type EndTransactionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// released is how many resources the transaction was holding. It is
	// zero for a transaction that never acquired anything, including one
	// the coordinator has never heard of, since ending an unknown
	// transaction is idempotent rather than an error.
	Released uint32 `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
}

func (x *EndTransactionResponse) Reset() {
	*x = EndTransactionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordinator_v1_coordinator_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndTransactionResponse) ProtoMessage() {}

func (x *EndTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndTransactionResponse.ProtoReflect.Descriptor instead.
func (*EndTransactionResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *EndTransactionResponse) GetReleased() uint32 {
	if x != nil {
		return x.Released
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordinator_v1_coordinator_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{5}
}

type HealthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// active_transactions and held_locks are operational visibility, not a
	// protocol guarantee. They are a point-in-time sample.
	ActiveTransactions uint32 `protobuf:"varint,1,opt,name=active_transactions,json=activeTransactions,proto3" json:"active_transactions,omitempty"`
	HeldLocks          uint32 `protobuf:"varint,2,opt,name=held_locks,json=heldLocks,proto3" json:"held_locks,omitempty"`
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordinator_v1_coordinator_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetActiveTransactions() uint32 {
	if x != nil {
		return x.ActiveTransactions
	}
	return 0
}

func (x *HealthResponse) GetHeldLocks() uint32 {
	if x != nil {
		return x.HeldLocks
	}
	return 0
}

var File_coordinator_v1_coordinator_proto protoreflect.FileDescriptor

var file_coordinator_v1_coordinator_proto_rawDesc = []byte{
	0x0a, 0x20, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x76, 0x31, 0x22, 0x50, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64,
	0x12, 0x30, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c,
	0x2e, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x22, 0x9d, 0x01, 0x0a, 0x0e, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x36,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x52, 0x08, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04,
	0x6d, 0x6f, 0x64, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3e, 0x0a, 0x15, 0x45, 0x6e, 0x64, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x25, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x16, 0x45, 0x6e, 0x64, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x64, 0x22, 0x0f, 0x0a,
	0x0d, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x60,
	0x0a, 0x0e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2f, 0x0a, 0x13, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x12, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x65, 0x6c, 0x64, 0x5f, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x68, 0x65, 0x6c, 0x64, 0x4c, 0x6f, 0x63, 0x6b, 0x73,
	0x2a, 0x54, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x6b, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x15,
	0x4c, 0x4f, 0x43, 0x4b, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x4c, 0x4f, 0x43, 0x4b, 0x5f,
	0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x53, 0x48, 0x41, 0x52, 0x45, 0x44, 0x10, 0x01, 0x12, 0x17, 0x0a,
	0x13, 0x4c, 0x4f, 0x43, 0x4b, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x45, 0x58, 0x43, 0x4c, 0x55,
	0x53, 0x49, 0x56, 0x45, 0x10, 0x02, 0x2a, 0x62, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x19, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52,
	0x43, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43,
	0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x53, 0x50, 0x41, 0x43, 0x45,
	0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x02, 0x32, 0x87, 0x02, 0x0a, 0x0f, 0x4c,
	0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x4a,
	0x0a, 0x07, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x12, 0x1e, 0x2e, 0x63, 0x6f, 0x6f, 0x72,
	0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x6f, 0x6f, 0x72,
	0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f, 0x0a, 0x0e, 0x45, 0x6e,
	0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x2e, 0x63,
	0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e,
	0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x06, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x4b, 0x5a, 0x49, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x4a, 0x61, 0x6d, 0x4a, 0x61, 0x6d, 0x7a, 0x7a, 0x7a, 0x2f, 0x73, 0x61, 0x66,
	0x65, 0x72, 0x2d, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72,
	0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_coordinator_v1_coordinator_proto_rawDescOnce sync.Once
	file_coordinator_v1_coordinator_proto_rawDescData = file_coordinator_v1_coordinator_proto_rawDesc
)

func file_coordinator_v1_coordinator_proto_rawDescGZIP() []byte {
	file_coordinator_v1_coordinator_proto_rawDescOnce.Do(func() {
		file_coordinator_v1_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(file_coordinator_v1_coordinator_proto_rawDescData)
	})
	return file_coordinator_v1_coordinator_proto_rawDescData
}

var file_coordinator_v1_coordinator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_coordinator_v1_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_coordinator_v1_coordinator_proto_goTypes = []any{
	(LockMode)(0),                  // 0: coordinator.v1.LockMode
	(ResourceType)(0),              // 1: coordinator.v1.ResourceType
	(*ResourceId)(nil),             // 2: coordinator.v1.ResourceId
	(*AcquireRequest)(nil),         // 3: coordinator.v1.AcquireRequest
	(*AcquireResponse)(nil),        // 4: coordinator.v1.AcquireResponse
	(*EndTransactionRequest)(nil),  // 5: coordinator.v1.EndTransactionRequest
	(*EndTransactionResponse)(nil), // 6: coordinator.v1.EndTransactionResponse
	(*HealthRequest)(nil),          // 7: coordinator.v1.HealthRequest
	(*HealthResponse)(nil),         // 8: coordinator.v1.HealthResponse
}
var file_coordinator_v1_coordinator_proto_depIdxs = []int32{
	1, // 0: coordinator.v1.ResourceId.type:type_name -> coordinator.v1.ResourceType
	2, // 1: coordinator.v1.AcquireRequest.resource:type_name -> coordinator.v1.ResourceId
	0, // 2: coordinator.v1.AcquireRequest.mode:type_name -> coordinator.v1.LockMode
	3, // 3: coordinator.v1.LockCoordinator.Acquire:input_type -> coordinator.v1.AcquireRequest
	5, // 4: coordinator.v1.LockCoordinator.EndTransaction:input_type -> coordinator.v1.EndTransactionRequest
	7, // 5: coordinator.v1.LockCoordinator.Health:input_type -> coordinator.v1.HealthRequest
	4, // 6: coordinator.v1.LockCoordinator.Acquire:output_type -> coordinator.v1.AcquireResponse
	6, // 7: coordinator.v1.LockCoordinator.EndTransaction:output_type -> coordinator.v1.EndTransactionResponse
	8, // 8: coordinator.v1.LockCoordinator.Health:output_type -> coordinator.v1.HealthResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_coordinator_v1_coordinator_proto_init() }
func file_coordinator_v1_coordinator_proto_init() {
	if File_coordinator_v1_coordinator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_coordinator_v1_coordinator_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ResourceId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordinator_v1_coordinator_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AcquireRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordinator_v1_coordinator_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AcquireResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordinator_v1_coordinator_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*EndTransactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordinator_v1_coordinator_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*EndTransactionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordinator_v1_coordinator_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*HealthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordinator_v1_coordinator_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*HealthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_coordinator_v1_coordinator_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coordinator_v1_coordinator_proto_goTypes,
		DependencyIndexes: file_coordinator_v1_coordinator_proto_depIdxs,
		EnumInfos:         file_coordinator_v1_coordinator_proto_enumTypes,
		MessageInfos:      file_coordinator_v1_coordinator_proto_msgTypes,
	}.Build()
	File_coordinator_v1_coordinator_proto = out.File
	file_coordinator_v1_coordinator_proto_rawDesc = nil
	file_coordinator_v1_coordinator_proto_goTypes = nil
	file_coordinator_v1_coordinator_proto_depIdxs = nil
}
