// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: coordinator/v1/coordinator.proto

// Package coordinator.v1 is the wire surface of the SAFER lock
// coordinator.
//
// The surface is deliberately small and strict-2PL-shaped.
//
// There is no BeginTransaction RPC. A transaction's identity is a UUID the
// worker generates locally, which costs nothing and cannot collide across
// workers; the coordinator creates transaction state lazily on the first
// Acquire. A separate Begin would add a round trip and a second failure
// mode (a transaction that exists on the coordinator but whose creating
// worker never learned it) for no gain in this phase.
//
// There is no per-resource Release. Under strict two-phase locking a
// transaction holds every lock it takes until it ends, so the only way to
// release is EndTransaction, which releases all of them at once. Offering
// early release would hand callers a way to violate the protocol.
//
// Transactions carry a lease. The coordinator is authoritative for the
// deadline; a worker renews it while it works. A passed deadline does not
// release anything by itself -- it only makes the transaction eligible for
// revocation, which is a deliberate, ordered process on the coordinator.
//
// Exclusive grants carry a fencing token. Shared grants do not: a stale
// reader cannot corrupt anything, and issuing tokens for readers would
// serialize them against each other for no benefit.

package coordinatorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LockCoordinator_Acquire_FullMethodName        = "/coordinator.v1.LockCoordinator/Acquire"
	LockCoordinator_EndTransaction_FullMethodName = "/coordinator.v1.LockCoordinator/EndTransaction"
	LockCoordinator_RenewLease_FullMethodName     = "/coordinator.v1.LockCoordinator/RenewLease"
	LockCoordinator_Health_FullMethodName         = "/coordinator.v1.LockCoordinator/Health"
)

// LockCoordinatorClient is the client API for LockCoordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LockCoordinatorClient interface {
	// Acquire blocks until the transaction holds the requested mode on the
	// resource. A cancelled or disconnected Acquire leaves the wait queue
	// and is never granted afterwards.
	Acquire(ctx context.Context, in *AcquireRequest, opts ...grpc.CallOption) (*AcquireResponse, error)
	// EndTransaction releases every lock the transaction holds. It is
	// idempotent, and workers call it on every path, including after an
	// Acquire whose response never arrived.
	EndTransaction(ctx context.Context, in *EndTransactionRequest, opts ...grpc.CallOption) (*EndTransactionResponse, error)
	// RenewLease extends a transaction's lease.
	//
	// It is idempotent: renewing repeatedly simply moves the deadline. It
	// fails once the transaction is being revoked or is gone, which is how
	// a worker learns it has lost its locks.
	RenewLease(ctx context.Context, in *RenewLeaseRequest, opts ...grpc.CallOption) (*RenewLeaseResponse, error)
	// Health reports that the coordinator is serving.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type lockCoordinatorClient struct {
	cc grpc.ClientConnInterface
}

func NewLockCoordinatorClient(cc grpc.ClientConnInterface) LockCoordinatorClient {
	return &lockCoordinatorClient{cc}
}

func (c *lockCoordinatorClient) Acquire(ctx context.Context, in *AcquireRequest, opts ...grpc.CallOption) (*AcquireResponse, error) {
	out := new(AcquireResponse)
	err := c.cc.Invoke(ctx, LockCoordinator_Acquire_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockCoordinatorClient) EndTransaction(ctx context.Context, in *EndTransactionRequest, opts ...grpc.CallOption) (*EndTransactionResponse, error) {
	out := new(EndTransactionResponse)
	err := c.cc.Invoke(ctx, LockCoordinator_EndTransaction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockCoordinatorClient) RenewLease(ctx context.Context, in *RenewLeaseRequest, opts ...grpc.CallOption) (*RenewLeaseResponse, error) {
	out := new(RenewLeaseResponse)
	err := c.cc.Invoke(ctx, LockCoordinator_RenewLease_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lockCoordinatorClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, LockCoordinator_Health_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LockCoordinatorServer is the server API for LockCoordinator service.
// All implementations must embed UnimplementedLockCoordinatorServer
// for forward compatibility
type LockCoordinatorServer interface {
	// Acquire blocks until the transaction holds the requested mode on the
	// resource. A cancelled or disconnected Acquire leaves the wait queue
	// and is never granted afterwards.
	Acquire(context.Context, *AcquireRequest) (*AcquireResponse, error)
	// EndTransaction releases every lock the transaction holds. It is
	// idempotent, and workers call it on every path, including after an
	// Acquire whose response never arrived.
	EndTransaction(context.Context, *EndTransactionRequest) (*EndTransactionResponse, error)
	// RenewLease extends a transaction's lease.
	//
	// It is idempotent: renewing repeatedly simply moves the deadline. It
	// fails once the transaction is being revoked or is gone, which is how
	// a worker learns it has lost its locks.
	RenewLease(context.Context, *RenewLeaseRequest) (*RenewLeaseResponse, error)
	// Health reports that the coordinator is serving.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedLockCoordinatorServer()
}

// UnimplementedLockCoordinatorServer must be embedded to have forward compatible implementations.
type UnimplementedLockCoordinatorServer struct {
}

func (UnimplementedLockCoordinatorServer) Acquire(context.Context, *AcquireRequest) (*AcquireResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Acquire not implemented")
}
func (UnimplementedLockCoordinatorServer) EndTransaction(context.Context, *EndTransactionRequest) (*EndTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndTransaction not implemented")
}
func (UnimplementedLockCoordinatorServer) RenewLease(context.Context, *RenewLeaseRequest) (*RenewLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewLease not implemented")
}
func (UnimplementedLockCoordinatorServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedLockCoordinatorServer) mustEmbedUnimplementedLockCoordinatorServer() {}

// UnsafeLockCoordinatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LockCoordinatorServer will
// result in compilation errors.
type UnsafeLockCoordinatorServer interface {
	mustEmbedUnimplementedLockCoordinatorServer()
}

func RegisterLockCoordinatorServer(s grpc.ServiceRegistrar, srv LockCoordinatorServer) {
	s.RegisterService(&LockCoordinator_ServiceDesc, srv)
}

func _LockCoordinator_Acquire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockCoordinatorServer).Acquire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockCoordinator_Acquire_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockCoordinatorServer).Acquire(ctx, req.(*AcquireRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockCoordinator_EndTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockCoordinatorServer).EndTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockCoordinator_EndTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockCoordinatorServer).EndTransaction(ctx, req.(*EndTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockCoordinator_RenewLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockCoordinatorServer).RenewLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockCoordinator_RenewLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockCoordinatorServer).RenewLease(ctx, req.(*RenewLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LockCoordinator_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LockCoordinatorServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LockCoordinator_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LockCoordinatorServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LockCoordinator_ServiceDesc is the grpc.ServiceDesc for LockCoordinator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LockCoordinator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coordinator.v1.LockCoordinator",
	HandlerType: (*LockCoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Acquire",
			Handler:    _LockCoordinator_Acquire_Handler,
		},
		{
			MethodName: "EndTransaction",
			Handler:    _LockCoordinator_EndTransaction_Handler,
		},
		{
			MethodName: "RenewLease",
			Handler:    _LockCoordinator_RenewLease_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _LockCoordinator_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coordinator/v1/coordinator.proto",
}
